# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bfe56bec-4230-4060-83b6-a53ef5ec49df";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bfe56bec-4230-4060-83b6-a53ef5ec49df".device = "/dev/disk/by-uuid/bfe56bec-4230-4060-83b6-a53ef5ec49df";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DF37-DCD8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-13d6600a-c71f-4a8c-8986-8f5e93554502"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
